# Site settings
title: La College Box
description: > # this means to ignore newlines until "baseurl:"
  La College Box CC
baseurl: "/contenu-college-box" # the subpath of your site, e.g. /blog/
url: "http://cgj33.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

college:
    dossier: francisco-goya
    nom: Francisco Goya