# Site settings
title: La College Box
description:  Projet College Box CDJ33
baseurl: "/contenu-college-box" # the subpath of your site, e.g. /blog/
url: "http://cgj33.github.io" # the base hostname & protocol for your site
author:
  facebook:     Conseil-départemental-des-Jeunes-de-la-Gironde
  twitter:      username

github_username : CDJ33
# Build settings
markdown: kramdown

college:
    dossier: francisco-goya
    nom: Francisco Goya